name: "Setup environment"
description: "Setup Java build environment"

runs:
  using: "composite"
  steps:
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'